CREATE TABLE FLAGELLA(
   ALPHA INTEGER,
   BETA INTEGER,
   NUMBER INTEGER);

CREATE TABLE TOUGHNESS(
   BETA INTEGER,
   GAMMA INTEGER,
   RANK TEXT
);

CREATE TABLE EXAMINED(
   GENOTYPE TEXT,
   CLASS TEXT
);

INSERT INTO TOUGHNESS VALUES (43,23,"d");
INSERT INTO TOUGHNESS VALUES (24,43,"b");
INSERT INTO TOUGHNESS VALUES (54,12,"b");
INSERT INTO TOUGHNESS VALUES (43,43,"a");
INSERT INTO TOUGHNESS VALUES (23,87,"d");
INSERT INTO TOUGHNESS VALUES (51,33,"c");
INSERT INTO TOUGHNESS VALUES (32,93,"c");
INSERT INTO TOUGHNESS VALUES (51,32,"a");

INSERT INTO FLAGELLA VALUES (12,43,1);
INSERT INTO FLAGELLA VALUES (33,24,3);
INSERT INTO FLAGELLA VALUES (34,54,2);
INSERT INTO FLAGELLA VALUES (32,43,2);
INSERT INTO FLAGELLA VALUES (34,23,1);
INSERT INTO FLAGELLA VALUES (63,51,3);
INSERT INTO FLAGELLA VALUES (22,32,1);
INSERT INTO FLAGELLA VALUES (81,51,2);



